Изменение. Добавка мышиных ушек и хвостика. Изменение названия, а также лого.
ZettaProtocol/Sirena pull request #11
Opened 2023-01-01 18:20 UTC by EvgenRP99

## Описание PR

**Скриншоты**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.

**Изменения**

:cl:
- add: Попытка добавления мышиных ушек и хвостика, как кастом и предмет. Изменение логотипа при входе в игру. Изменение файла манифест с Corvax на Sirena!
- remove: Моя психика!

2023-01-02 13:39 UTC, ZettaProtocol requested changes
Измени это, а так же нужно добавить англ. локализацию. У нас есть отдельные папки где хранится перевод. Не нужно мне закидывать это в общий котёл.

2023-01-02 13:39 UTC, ZettaProtocol commented on README.md
> +[Наш Discord](https://discord.gg/dC7qyawKQB) | [Основная вики русскоязычного коммьюнити](https://wiki.station14.ru) | [Steam](https://store.steampowered.com/app/1255460/Space_Station_14/) | [Клиент б
Приглашение не действительно

2023-01-02 13:39 UTC, ZettaProtocol commented on README.md
> +В случае если вы хотите добавить новый контент обсудите его необходимость на нашем сервере [Discord](https://discord.gg/dC7qyawKQB).
Приглашение не действительно

2023-01-02 13:39 UTC, ZettaProtocol commented on README.md
> +Большинство ассетов лицензированы под [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/), если не указано иное. Ассеты имеют свою лицензию и авторские права в файле метаданных.
Почему удалил пример?

2023-01-02 13:39 UTC, ZettaProtocol commented on Resources/Locale/ru-RU/markings/cat.ftl
> +marking-MouseTail = Мышиный хвост
Отдельным это файлом бляха. Ошибки вызываешь!

2023-01-02 13:39 UTC, ZettaProtocol commented on Resources/Locale/ru-RU/markings/cat.ftl
> +marking-MouseTail = Мышиный хвост
Или меняй обратно

2023-01-02 13:39 UTC, ZettaProtocol commented on Resources/Locale/ru-RU/markings/mouse.ftl
> +marking-MouseEars = Мышиные ушки
Вот как тут. Но ты не туда закинул. У нас для перевода своих вещей отдельная папка

2023-01-02 13:39 UTC, ZettaProtocol commented on Resources/Textures/Clothing/Head/Hats/mouseears.rsi/meta.json
> +  "copyright": "created Loren"
Точнее укажи кто это сделал. Пример ниже
```suggestion
  "copyright": "created by Discord member Neko Dar#8948 (783449596986785832)"
```

2023-01-02 13:39 UTC, ZettaProtocol commented on Resources/Textures/Mobs/Customization/mouse_parts.rsi/meta.json
> +  "copyright": created Loren
Аналогично тому что писал раньше

2023-01-02 13:51 UTC, ZettaProtocol commented on Resources/Textures/Clothing/Head/Hats/mouseears.rsi/meta.json
> +  "copyright": "created Loren"
Ах, да тут ещё не в той папке

2023-01-02 13:52 UTC, ZettaProtocol commented on Resources/Textures/Mobs/Customization/mouse_parts.rsi/meta.json
> +  "copyright": created Loren
Ах, да тут ещё не в той папке

2023-01-02 13:52 UTC, EvgenRP99 commented on README.md
> +Большинство ассетов лицензированы под [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/), если не указано иное. Ассеты имеют свою лицензию и авторские права в файле метаданных.
Потому что он по большей части связан с Корваксом...хотя...ладно...сейчас добавлю другой пример

2023-01-02 13:52 UTC, EvgenRP99 commented on Resources/Locale/ru-RU/markings/cat.ftl
> +marking-MouseTail = Мышиный хвост
Умф...типа как?

2023-01-02 13:53 UTC, ZettaProtocol commented on README.md
> +Большинство ассетов лицензированы под [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/), если не указано иное. Ассеты имеют свою лицензию и авторские права в файле метаданных.
> Потому что он по большей части связан с Корваксом...хотя...ладно...сейчас добавлю другой пример

А что мешает скинуть пример на наш код?

2023-01-02 13:53 UTC, EvgenRP99 commented on Resources/Locale/ru-RU/markings/mouse.ftl
> +marking-MouseEars = Мышиные ушки
Умф...понял...а это которая?

2023-01-02 13:53 UTC, EvgenRP99 commented on Resources/Textures/Clothing/Head/Hats/mouseears.rsi/meta.json
> +  "copyright": "created Loren"
Окей...

2023-01-02 13:54 UTC, ZettaProtocol commented on Resources/Locale/ru-RU/markings/cat.ftl
> +marking-MouseTail = Мышиный хвост
> Умф...типа как?

Замени обратно на то что было

2023-01-02 13:54 UTC, EvgenRP99 commented on README.md
> +[Наш Discord](https://discord.gg/dC7qyawKQB) | [Основная вики русскоязычного коммьюнити](https://wiki.station14.ru) | [Steam](https://store.steampowered.com/app/1255460/Space_Station_14/) | [Клиент б
Сейчас исправлю

2023-01-02 13:54 UTC, EvgenRP99 commented on README.md
> +В случае если вы хотите добавить новый контент обсудите его необходимость на нашем сервере [Discord](https://discord.gg/dC7qyawKQB).
Это тоже

2023-01-02 13:56 UTC, ZettaProtocol commented on Resources/Locale/ru-RU/markings/mouse.ftl
> +marking-MouseEars = Мышиные ушки
> Умф...понял...а это которая?

В твоём случае это Resources\Locale\ru-RU\sirena

2023-01-02 13:56 UTC, EvgenRP99 commented on README.md
> +Большинство ассетов лицензированы под [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/), если не указано иное. Ассеты имеют свою лицензию и авторские права в файле метаданных.
Ну...именно о нем я и говорю

2023-01-02 14:11 UTC, ZettaProtocol commented
Кстати. Поменяй спрайты. Ухо снаружи не должно иметь ухо внутри. Они накладываются друг на друга

2023-01-04 07:28 UTC, ZettaProtocol commented
И да, обнови свою локалку, у тебя она старая

2023-01-04 11:27 UTC, EvgenRP99 commented
А как обновить?

2023-01-05 19:02 UTC, ZettaProtocol commented
Переезд на новый гит
https://github.com/ZettaProtocol/SS14-Sirena

2023-01-05 19:02 UTC, closed without merging